# Fichiers

In [1]:
# module moderne de Python 3
from pathlib import Path
# module plus ancien maintenu : os.

# opération de haut niveau : copie, copie récursive, suppression récursive
import shutil

import csv
import json

import pandas as pd

from datetime import date, datetime, timedelta

## Système de fichiers

In [2]:
data_path = Path("data")
data_path

WindowsPath('data')

In [3]:
data_path.exists() and data_path.is_dir()

True

In [4]:
current_dir = Path(".")
current_dir

WindowsPath('.')

In [5]:
print(current_dir.absolute())
print(data_path.absolute())

c:\Users\matth\Documents\Formation\Python\stage_python20260615_poo
c:\Users\matth\Documents\Formation\Python\stage_python20260615_poo\data

In [6]:
data_input_dir = 'C:\\Input\\data'
data_input_path = Path(data_input_dir)
data_input_path

WindowsPath('C:/Input/data')

In [7]:
data_input_dir = 'C:/Input/data'
data_input_path = Path(data_input_dir)
data_input_path

WindowsPath('C:/Input/data')

In [8]:
backup_path = data_path / "backup" / f"{date.today()}"
backup_path

WindowsPath('data/backup/2026-06-18')

In [9]:
backup_path.exists()

False

In [10]:
backup_path.mkdir(parents=True, exist_ok=True)
backup_path.exists() and backup_path.is_dir()

True

In [11]:
list(data_path.iterdir())

[WindowsPath('data/backup'),
 WindowsPath('data/dummy.txt'),
 WindowsPath('data/sauvegarde'),
 WindowsPath('data/villes.csv'),
 WindowsPath('data/villes100k.csv'),
 WindowsPath('data/villes100k.json'),
 WindowsPath('data/villes100k.xlsx'),
 WindowsPath('data/villes100k.xml'),
 WindowsPath('data/villes100k_win1252.csv'),
 WindowsPath('data/villes_fr.csv'),
 WindowsPath('data/villes_top5.csv')]

In [12]:
for p in data_path.iterdir():
    print(p)

data\backup
data\dummy.txt
data\sauvegarde
data\villes.csv
data\villes100k.csv
data\villes100k.json
data\villes100k.xlsx
data\villes100k.xml
data\villes100k_win1252.csv
data\villes_fr.csv
data\villes_top5.csv

In [13]:
for p in data_path.glob("villes100k*.*"):
    stats = p.stat()
    dt_creation = datetime.fromtimestamp(stats.st_birthtime)
    dt_modification = datetime.fromtimestamp(stats.st_mtime)
    dt_access = datetime.fromtimestamp(stats.st_atime)
    print(p)
    print(f"\t- fichier data : {p.is_file()}")
    print(f"\t- taille : {stats.st_size} o")
    print(f"\t- date création : {dt_creation}")
    print(f"\t- date dernière modif : {dt_modification}")
    print(f"\t- date dernier accès : {dt_access}")
    shutil.copy2(p, backup_path)

data\villes100k.csv
	- fichier data : True
	- taille : 2162 o
	- date création : 2026-06-18 08:56:09.144640
	- date dernière modif : 2026-06-18 08:57:25.261640
	- date dernier accès : 2026-06-18 11:55:33.054391
data\villes100k.json
	- fichier data : True
	- taille : 7707 o
	- date création : 2026-06-18 08:56:09.154618
	- date dernière modif : 2026-06-18 08:57:25.271639
	- date dernier accès : 2026-06-18 09:05:47.024020
data\villes100k.xlsx
	- fichier data : True
	- taille : 7274 o
	- date création : 2026-06-18 08:56:31.675221
	- date dernière modif : 2026-06-18 08:57:25.629488
	- date dernier accès : 2026-06-18 10:30:22.841061
data\villes100k.xml
	- fichier data : True
	- taille : 12089 o
	- date création : 2026-06-18 08:48:52.957649
	- date dernière modif : 2026-06-18 08:57:25.644487
	- date dernier accès : 2026-06-18 09:05:55.410886
data\villes100k_win1252.csv
	- fichier data : True
	- taille : 2141 o
	- date création : 2026-06-18 08:56:09.145640
	- date dernière modif : 2026-06-18 08:57:25.262643
	- date dernier accès : 2026-06-18 09:05:41.137468

In [14]:
dt_epoch = datetime(1970, 1, 1)
dt_epoch + timedelta(seconds=1781765769.14464)

datetime.datetime(2026, 6, 18, 6, 56, 9, 144640)

In [15]:
new_path = data_path / 'sauvegarde'
if not new_path.exists():
    backup_path.parent.rename(new_path)
    print("Renommage avec succès")
else:
    print(f"Echec renommage: {new_path} existe déjà")

Echec renommage: data\sauvegarde existe déjà

In [16]:
pytest_cache_path = Path('.pytest_cache')
if pytest_cache_path.exists() and pytest_cache_path.is_dir():
    print("Suppression:", pytest_cache_path)
    # pytest_cache_path.rmdir() # ok if empty
    shutil.rmtree(pytest_cache_path)
    print("Done")

In [17]:
dummy_path = data_path / "dummy.txt"
dummy_path.touch()
dummy_path.exists() and dummy_path.is_file()

True

In [18]:
dummy_path.unlink()
assert not dummy_path.exists()

## Lecture et Ecriture de fichiers

### Builtin open

In [19]:
# default mode : r (read) + t (text)
f = open('data/villes100k.csv', encoding='utf-8')
f

In [20]:
f.readline()

'nom_standard,nom_sans_pronom,dep_code,dep_nom,code_postal,population,superficie_km2\n'

In [21]:
# f est un iterator sur le contenu du fichier, ligne par ligne
for line in f:
    print(line, end='')

Nice,Nice,06,Alpes-Maritimes,06000,348085,74
Aix-en-Provence,Aix-en-Provence,13,Bouches-du-Rhône,13100,147478,188
Marseille,Marseille,13,Bouches-du-Rhône,13000,873076,241
Caen,Caen,14,Calvados,14000,108200,26
Dijon,Dijon,21,Côte-d'Or,21000,159346,42
Besançon,Besançon,25,Doubs,25000,119198,65
Brest,Brest,29,Finistère,29200,139619,49
Nîmes,Nîmes,30,Gard,30900,148104,161
Toulouse,Toulouse,31,Haute-Garonne,31100,504078,118
Bordeaux,Bordeaux,33,Gironde,33300,261804,50
Montpellier,Montpellier,34,Hérault,34080,302454,57
Rennes,Rennes,35,Ille-et-Vilaine,35700,225081,50
Tours,Tours,37,Indre-et-Loire,37100,137658,33
Grenoble,Grenoble,38,Isère,38000,157477,19
Saint-Étienne,Saint-Étienne,42,Loire,42100,172718,80
Nantes,Nantes,44,Loire-Atlantique,44200,323204,66
Orléans,Orléans,45,Loiret,45000,116617,28
Angers,Angers,49,Maine-et-Loire,49000,157175,44
Reims,Reims,51,Marne,51100,179380,47
Nancy,Nancy,54,Meurthe-et-Moselle,54100,104260,15
Metz,Metz,57,Moselle,57070,120874,42
Lille,Lille,59,Nord,59260,236710,35
Clermont-Ferrand,Clermont-Ferrand,63,Puy-de-Dôme,63100,147327,43
Perpignan,Perpignan,66,Pyrénées-Orientales,66000,119656,68
Strasbourg,Strasbourg,67,Bas-Rhin,67000,291313,78
Mulhouse,Mulhouse,68,Haut-Rhin,68200,106341,22
Lyon,Lyon,69,Rhône,69000,522250,48
Villeurbanne,Villeurbanne,69,Rhône,69100,156928,15
Le Mans,Mans,72,Sarthe,72100,145004,53
Annecy,Annecy,74,Haute-Savoie,74000,131715,16
Paris,Paris,75,Paris,75000,2133111,105
Le Havre,Havre,76,Seine-Maritime,76620,166058,55
Rouen,Rouen,76,Seine-Maritime,76100,114083,21
Amiens,Amiens,80,Somme,80090,133625,50
Toulon,Toulon,83,Var,83000,180452,44
Limoges,Limoges,87,Haute-Vienne,87100,129760,80
Boulogne-Billancourt,Boulogne-Billancourt,92,Hauts-de-Seine,92100,119808,6
Montreuil,Montreuil,93,Seine-Saint-Denis,93100,111455,9
Saint-Denis,Saint-Denis,93,Seine-Saint-Denis,93210,113942,12
Argenteuil,Argenteuil,95,Val-d'Oise,95100,107221,17
Saint-Denis,Saint-Denis,974,La Réunion,97400,154765,142
Saint-Paul,Saint-Paul,974,La Réunion,97411,105240,240

In [22]:
f.close()

In [23]:
with open('data/villes100k.csv', encoding='utf-8') as f:
    headers = f.readline().strip()
    # raise ValueError("Dummy error")
    # data = list(f) # lignes en l'état (avec \n)
    data = list(line.strip() for line in f)
# auto : f.close() même si il y a exception
assert f.closed
print(headers)
for line in data[:3]:
    print(line)

nom_standard,nom_sans_pronom,dep_code,dep_nom,code_postal,population,superficie_km2
Nice,Nice,06,Alpes-Maritimes,06000,348085,74
Aix-en-Provence,Aix-en-Provence,13,Bouches-du-Rhône,13100,147478,188
Marseille,Marseille,13,Bouches-du-Rhône,13000,873076,241

In [24]:
ville_infos = line.split(',')
ville_infos

['Marseille', 'Marseille', '13', 'Bouches-du-Rhône', '13000', '873076', '241']

In [25]:
';'.join(ville_infos)

'Marseille;Marseille;13;Bouches-du-Rhône;13000;873076;241'

In [26]:
output_path = data_path / "villes_top5.csv"

new_headers = headers.replace(',',';')

with open(output_path, encoding='cp1252', mode='w') as f:
    f.write(new_headers)
    f.write('\n')
    for d in data[:5]:
        new_d = d.replace(',',';')
        f.write(new_d)
        f.write('\n')

print("l'écriture dans le fichier est terminée")

l'écriture dans le fichier est terminée

### module `csv`

In [27]:
with open(output_path, encoding='cp1252') as f:
    # adaptateur
    reader = csv.reader(f, delimiter=';')  # or DictReader
    # entetes
    headers = next(reader)
    print(headers)
    print()
    # contenu
    for ville in reader:
        print(ville)
# auto => close

['nom_standard', 'nom_sans_pronom', 'dep_code', 'dep_nom', 'code_postal', 'population', 'superficie_km2']

['Nice', 'Nice', '06', 'Alpes-Maritimes', '06000', '348085', '74']
['Aix-en-Provence', 'Aix-en-Provence', '13', 'Bouches-du-Rhône', '13100', '147478', '188']
['Marseille', 'Marseille', '13', 'Bouches-du-Rhône', '13000', '873076', '241']
['Caen', 'Caen', '14', 'Calvados', '14000', '108200', '26']
['Dijon', 'Dijon', '21', "Côte-d'Or", '21000', '159346', '42']

### pandas
- I/O : csv, json, xml, excel, sql, ..., data python (list/tuple/dict)
- traitement : nettoyage, transformation, croisement

In [28]:
dtypes = {
    'dep_code': str,
    'code_postal': str
}
villes = pd.read_csv('data/villes100k.csv', encoding='utf-8', dtype=dtypes)
villes.head()

,nom_standard,nom_sans_pronom,dep_code,dep_nom,code_postal,population,superficie_km2
0,Nice,Nice,06,Alpes-Maritimes,06000,348085,74
1,Aix-en-Provence,Aix-en-Provence,13,Bouches-du-Rhône,13100,147478,188
2,Marseille,Marseille,13,Bouches-du-Rhône,13000,873076,241
3,Caen,Caen,14,Calvados,14000,108200,26
4,Dijon,Dijon,21,Côte-d'Or,21000,159346,42

In [29]:
villes.info()

<class 'pandas.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nom_standard     42 non-null     str
 1   nom_sans_pronom  42 non-null     str
 2   dep_code         42 non-null     str
 3   dep_nom          42 non-null     str
 4   code_postal      42 non-null     str
 5   population       42 non-null     int64
 6   superficie_km2   42 non-null     int64
dtypes: int64(2), str(5)
memory usage: 2.4 KB

In [30]:
villes.describe()

         population  superficie_km2
count  4.200000e+01       42.000000
mean   2.436345e+05       63.190476
std    3.317333e+05       56.520766
min    1.042600e+05        6.000000
25%    1.196940e+05       26.500000
50%    1.477910e+05       48.500000
75%    2.139238e+05       72.500000
max    2.133111e+06      241.000000

In [31]:
villes.sort_values('population', ascending=False)

,nom_standard,nom_sans_pronom,dep_code,dep_nom,code_postal,population,superficie_km2
30,Paris,Paris,75,Paris,75000,2133111,105
2,Marseille,Marseille,13,Bouches-du-Rhône,13000,873076,241
26,Lyon,Lyon,69,Rhône,69000,522250,48
8,Toulouse,Toulouse,31,Haute-Garonne,31100,504078,118
0,Nice,Nice,06,Alpes-Maritimes,06000,348085,74
15,Nantes,Nantes,44,Loire-Atlantique,44200,323204,66
10,Montpellier,Montpellier,34,Hérault,34080,302454,57
24,Strasbourg,Strasbourg,67,Bas-Rhin,67000,291313,78
9,Bordeaux,Bordeaux,33,Gironde,33300,261804,50
21,Lille,Lille,59,Nord,59260,236710,35
11,Rennes,Rennes,35,Ille-et-Vilaine,35700,225081,50
34,Toulon,Toulon,83,Var,83000,180452,44
18,Reims,Reims,51,Marne,51100,179380,47
14,Saint-Étienne,Saint-Étienne,42,Loire,42100,172718,80
31,Le Havre,Havre,76,Seine-Maritime,76620,166058,55
4,Dijon,Dijon,21,Côte-d'Or,21000,159346,42
13,Grenoble,Grenoble,38,Isère,38000,157477,19
17,Angers,Angers,49,Maine-et-Loire,49000,157175,44
27,Villeurbanne,Villeurbanne,69,Rhône,69100,156928,15
40,Saint-Denis,Saint-Denis,974,La Réunion,97400,154765,142
7,Nîmes,Nîmes,30,Gard,30900,148104,161
1,Aix-en-Provence,Aix-en-Provence,13,Bouches-du-Rhône,13100,147478,188
22,Clermont-Ferrand,Clermont-Ferrand,63,Puy-de-Dôme,63100,147327,43
28,Le Mans,Mans,72,Sarthe,72100,145004,53
6,Brest,Brest,29,Finistère,29200,139619,49
12,Tours,Tours,37,Indre-et-Loire,37100,137658,33
33,Amiens,Amiens,80,Somme,80090,133625,50
29,Annecy,Annecy,74,Haute-Savoie,74000,131715,16
35,Limoges,Limoges,87,Haute-Vienne,87100,129760,80
20,Metz,Metz,57,Moselle,57070,120874,42
36,Boulogne-Billancourt,Boulogne-Billancourt,92,Hauts-de-Seine,92100,119808,6
23,Perpignan,Perpignan,66,Pyrénées-Orientales,66000,119656,68
5,Besançon,Besançon,25,Doubs,25000,119198,65
16,Orléans,Orléans,45,Loiret,45000,116617,28
32,Rouen,Rouen,76,Seine-Maritime,76100,114083,21
38,Saint-Denis,Saint-Denis,93,Seine-Saint-Denis,93210,113942,12
37,Montreuil,Montreuil,93,Seine-Saint-Denis,93100,111455,9
3,Caen,Caen,14,Calvados,14000,108200,26
39,Argenteuil,Argenteuil,95,Val-d'Oise,95100,107221,17
25,Mulhouse,Mulhouse,68,Haut-Rhin,68200,106341,22
41,Saint-Paul,Saint-Paul,974,La Réunion,97411,105240,240
19,Nancy,Nancy,54,Meurthe-et-Moselle,54100,104260,15

In [32]:
villes.sort_values(['dep_code', 'population'], ascending=[True, False])

,nom_standard,nom_sans_pronom,dep_code,dep_nom,code_postal,population,superficie_km2
0,Nice,Nice,06,Alpes-Maritimes,06000,348085,74
2,Marseille,Marseille,13,Bouches-du-Rhône,13000,873076,241
1,Aix-en-Provence,Aix-en-Provence,13,Bouches-du-Rhône,13100,147478,188
3,Caen,Caen,14,Calvados,14000,108200,26
4,Dijon,Dijon,21,Côte-d'Or,21000,159346,42
5,Besançon,Besançon,25,Doubs,25000,119198,65
6,Brest,Brest,29,Finistère,29200,139619,49
7,Nîmes,Nîmes,30,Gard,30900,148104,161
8,Toulouse,Toulouse,31,Haute-Garonne,31100,504078,118
9,Bordeaux,Bordeaux,33,Gironde,33300,261804,50
10,Montpellier,Montpellier,34,Hérault,34080,302454,57
11,Rennes,Rennes,35,Ille-et-Vilaine,35700,225081,50
12,Tours,Tours,37,Indre-et-Loire,37100,137658,33
13,Grenoble,Grenoble,38,Isère,38000,157477,19
14,Saint-Étienne,Saint-Étienne,42,Loire,42100,172718,80
15,Nantes,Nantes,44,Loire-Atlantique,44200,323204,66
16,Orléans,Orléans,45,Loiret,45000,116617,28
17,Angers,Angers,49,Maine-et-Loire,49000,157175,44
18,Reims,Reims,51,Marne,51100,179380,47
19,Nancy,Nancy,54,Meurthe-et-Moselle,54100,104260,15
20,Metz,Metz,57,Moselle,57070,120874,42
21,Lille,Lille,59,Nord,59260,236710,35
22,Clermont-Ferrand,Clermont-Ferrand,63,Puy-de-Dôme,63100,147327,43
23,Perpignan,Perpignan,66,Pyrénées-Orientales,66000,119656,68
24,Strasbourg,Strasbourg,67,Bas-Rhin,67000,291313,78
25,Mulhouse,Mulhouse,68,Haut-Rhin,68200,106341,22
26,Lyon,Lyon,69,Rhône,69000,522250,48
27,Villeurbanne,Villeurbanne,69,Rhône,69100,156928,15
28,Le Mans,Mans,72,Sarthe,72100,145004,53
29,Annecy,Annecy,74,Haute-Savoie,74000,131715,16
30,Paris,Paris,75,Paris,75000,2133111,105
31,Le Havre,Havre,76,Seine-Maritime,76620,166058,55
32,Rouen,Rouen,76,Seine-Maritime,76100,114083,21
33,Amiens,Amiens,80,Somme,80090,133625,50
34,Toulon,Toulon,83,Var,83000,180452,44
35,Limoges,Limoges,87,Haute-Vienne,87100,129760,80
36,Boulogne-Billancourt,Boulogne-Billancourt,92,Hauts-de-Seine,92100,119808,6
38,Saint-Denis,Saint-Denis,93,Seine-Saint-Denis,93210,113942,12
37,Montreuil,Montreuil,93,Seine-Saint-Denis,93100,111455,9
39,Argenteuil,Argenteuil,95,Val-d'Oise,95100,107221,17
40,Saint-Denis,Saint-Denis,974,La Réunion,97400,154765,142
41,Saint-Paul,Saint-Paul,974,La Réunion,97411,105240,240

In [33]:
total_population = villes.population.sum()
print(f"{total_population:_}")

10_232_650

In [34]:
total_population = villes['population'].sum()
print(f"{total_population:_}")

10_232_650

In [35]:
villes[['population', 'superficie_km2']].sum()

population        10232650
superficie_km2        2654
dtype: int64

In [36]:
# extraction à partir des indexes de lignes et de colonnes
villes.iloc[:3, :3]

      nom_standard  nom_sans_pronom dep_code
0             Nice             Nice       06
1  Aix-en-Provence  Aix-en-Provence       13
2        Marseille        Marseille       13

In [37]:
dept = '13'
villes.loc[villes.dep_code == dept]

,nom_standard,nom_sans_pronom,dep_code,dep_nom,code_postal,population,superficie_km2
1,Aix-en-Provence,Aix-en-Provence,13,Bouches-du-Rhône,13100,147478,188
2,Marseille,Marseille,13,Bouches-du-Rhône,13000,873076,241

In [38]:
villes.dep_code == dept

0     False
1      True
2      True
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
Name: dep_code, dtype: bool

In [39]:
villes.loc[villes.superficie_km2 >= 200]

,nom_standard,nom_sans_pronom,dep_code,dep_nom,code_postal,population,superficie_km2
2,Marseille,Marseille,13,Bouches-du-Rhône,13000,873076,241
41,Saint-Paul,Saint-Paul,974,La Réunion,97411,105240,240

In [40]:
depts = ['13', '59', '31', '92', '95']
villes.loc[villes.dep_code.isin(depts)]

,nom_standard,nom_sans_pronom,dep_code,dep_nom,code_postal,population,superficie_km2
1,Aix-en-Provence,Aix-en-Provence,13,Bouches-du-Rhône,13100,147478,188
2,Marseille,Marseille,13,Bouches-du-Rhône,13000,873076,241
8,Toulouse,Toulouse,31,Haute-Garonne,31100,504078,118
21,Lille,Lille,59,Nord,59260,236710,35
36,Boulogne-Billancourt,Boulogne-Billancourt,92,Hauts-de-Seine,92100,119808,6
39,Argenteuil,Argenteuil,95,Val-d'Oise,95100,107221,17

In [41]:
type(villes)

pandas.DataFrame

In [42]:
type(villes.population)

pandas.Series

In [43]:
villes.loc[villes.nom_standard.str.contains(r"[^-]+-[^-]+")]

,nom_standard,nom_sans_pronom,dep_code,dep_nom,code_postal,population,superficie_km2
1,Aix-en-Provence,Aix-en-Provence,13,Bouches-du-Rhône,13100,147478,188
14,Saint-Étienne,Saint-Étienne,42,Loire,42100,172718,80
22,Clermont-Ferrand,Clermont-Ferrand,63,Puy-de-Dôme,63100,147327,43
36,Boulogne-Billancourt,Boulogne-Billancourt,92,Hauts-de-Seine,92100,119808,6
38,Saint-Denis,Saint-Denis,93,Seine-Saint-Denis,93210,113942,12
40,Saint-Denis,Saint-Denis,974,La Réunion,97400,154765,142
41,Saint-Paul,Saint-Paul,974,La Réunion,97411,105240,240

In [45]:
villes.loc[villes.nom_standard.str.contains(r"(?:[^-]+-[^-]+){2,}")]

,nom_standard,nom_sans_pronom,dep_code,dep_nom,code_postal,population,superficie_km2
1,Aix-en-Provence,Aix-en-Provence,13,Bouches-du-Rhône,13100,147478,188